<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dd_districts')->insert([
            ['state_id' => 1, 'name' => 'Batu Pahat', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Johor Bahru', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Kluang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Kota Tinggi', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Kulai', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Ledang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Mersing', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Muar', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Pontian', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Segamat', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 1, 'name' => 'Tangkak', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Baling', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Bandar Baharu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Kota Setar', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Kuala Muda', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Kubang Pasu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Kulim', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Langkawi', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Padang Terap', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Pendang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Sik', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 2, 'name' => 'Yan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Bachok', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Gua Musang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Jeli', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Jerteh', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Kota Bharu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Kuala Krai', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Machang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Pasir Mas', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Pasir Puteh', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Tanah Merah', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 3, 'name' => 'Tumpat', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 4, 'name' => 'Cheras', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 4, 'name' => 'Kuala Lumpur', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 5, 'name' => 'Labuan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 6, 'name' => 'Alor Gajah', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 6, 'name' => 'Jasin', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 6, 'name' => 'Melaka Tengah', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Gemas', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Jelebu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Jempol', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Kuala Pilah', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Nilai', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Port Dickson', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Rembau', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Seremban', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 7, 'name' => 'Tampin', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Bentong', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Bera', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Cameron Highlands', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Jerantut', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Kuala Lipis', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Kuantan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Lipis', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Maran', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Pekan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Raub', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Rompin', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 8, 'name' => 'Temerloh', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Bagan Datuk', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Batang Padang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Hilir Perak', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Hulu Perak', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Kampar', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Kerian', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Kinta', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Kuala Kangsar', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Larut, Matang dan Selama', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Manjung', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Muallim', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Pengkalan Hulu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Perak Tengah', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 9, 'name' => 'Taiping', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 10, 'name' => 'Arau', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 10, 'name' => 'Perlis', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Barat Daya', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Bukit Gedong', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Butterworth', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Lebuh Fell', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Seberang Perai Selatan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Seberang Perai Tengah', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Seberang Perai Utara', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Sungai Ara', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 11, 'name' => 'Timur Laut', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 12, 'name' => 'Putrajaya', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Beaufort', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Beluran', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kelabakan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Keningau', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kinabatangan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kota Belud', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kota Kinabalu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kota Marudu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kuala Penyu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kudat', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Kunak', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Lahad Datu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Membakut', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Nabawan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Papar', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Penampang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Pensiangan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Pitas', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Ranau', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Sandakan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Semporna', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Sipitang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Sook', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Tambunan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Tawau', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Teluk Sepanggar', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Telupid', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Tenom', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Tongod', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 13, 'name' => 'Tuaran', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Betong', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Bintulu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Kapit', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Kuching', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Limbang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Miri', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Mukah', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Samarahan', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Sarikei', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Serian', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Sibu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 14, 'name' => 'Sri Aman', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Batu Caves', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Gombak', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Hulu Langat', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Hulu Selangor', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Klang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Kuala Langat', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Kuala Selangor', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Petaling', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Rawang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Sabak Bernam', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Selatan Selangor', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Sepang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 15, 'name' => 'Sungai Buloh', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Besut', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Dungun', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Hulu Terengganu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Kemaman', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Kerteh', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Kota Bharu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Kuala Nerus', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Kuala Terengganu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Marang', 'created_at' => new Carbon(), 'updated_at' => new Carbon()],
            ['state_id' => 16, 'name' => 'Setiu', 'created_at' => new Carbon(), 'updated_at' => new Carbon()]
        ]);
    }
}
