<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ParishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dd_parishes')->insert([
            ["state_id" => 1, "district_id" => 1, "name" => "Ayer Hitam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Bagan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Bandar Penggaram", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Batu Pahat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Linau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Minyak Beku", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Parit Raja", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Parit Sulong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Peserai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Pt Yaani", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Rengit", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Semarang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Semerah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Senggarang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Simpang Kanan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Simpang Kiri", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Sri Gading", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Sri Medan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Sungai Kluang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 1, "name" => "Yong Peng", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Bandar Baru Uda", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Bandar Johor Bahru", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Johor Jaya", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Kempas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Larkin", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Masai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Nusajaya", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Pengkalan Rinting", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Permas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Plentong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Puteri Wangsa", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Skudai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Stulang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Tanjung Puteri", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Tebrau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 2, "name" => "Tiram", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Kahang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Kluang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Layang Layang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Machap", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Mahkota", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Mengkibol", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Paloh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Rengam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 3, "name" => "Ulu Benut", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 4, "name" => "Johor Lama", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 4, "name" => "Kota Tinggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 4, "name" => "Nam Heng", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 4, "name" => "Pengerang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 4, "name" => "Sedili Besar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 4, "name" => "Sedili Kechil", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 4, "name" => "Ulu Sungai Johor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 5, "name" => "Bukit Batu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 5, "name" => "Bukit Permai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 5, "name" => "Kulai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 5, "name" => "Kulaijaya", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 5, "name" => "Senai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 6, "name" => "Bukit Serampang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 6, "name" => "Grisek", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 6, "name" => "Kesang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 6, "name" => "Kundang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 6, "name" => "Ledang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 6, "name" => "Serom", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 6, "name" => "Tangkak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 7, "name" => "Endau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 7, "name" => "Mersing", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 7, "name" => "Padang Endau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 7, "name" => "Pulau Babi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Ayer Hitam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Bakri", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Bandar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Bukit Kepong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Jorak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Lenga", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Muar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Pagoh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Parit Bakar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Parit Jawa", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Sri Menanti", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Sungai Balang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Sungai Terap", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 8, "name" => "Tangkak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Api Api", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Ayer Baloi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Ayer Masin", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Benut", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Jeram Batu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Pekan Nenas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Pontian", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Rimba Terjun", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Serkat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Sungai Karang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Sungai Pinggan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 9, "name" => "Teluk Karang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Bekok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Buloh Kasap", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Gemas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Jabi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Jemantah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Kemelah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Labis", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Pemanis", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Pogoh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Segamat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Sermin", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Sungai Segamat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 1, "district_id" => 10, "name" => "Tenang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Bakai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Baling", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Bongor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Kuala Ketil", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Kupang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Malau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Parit Panjang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Pulai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Siong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Tawar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 12, "name" => "Telui Kanan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 13, "name" => "Bagan Samak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 13, "name" => "Bandar Baharu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 13, "name" => "Kuala Selama", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 13, "name" => "Relau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 13, "name" => "Serdang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 13, "name" => "Sungai Batu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Alor Merah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Anak Bukit", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Bukit Derang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Bukit Pinang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Derga", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Gunong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Kota Setar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Lengkuas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Lepai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Lesong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Pengkalan Kundor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Pokok Sena", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Pumpong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Tajar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 14, "name" => "Titi Gajah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Bedong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Bujang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Bukit Meriam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Gurun", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Haji Kudong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Kuala Kedah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Kuala Muda", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Merbok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Pekula", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Pinang Tunggal", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Semeling", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Sidam Kiri", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 15, "name" => "Sungai Petani", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Binjal", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Changloon", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Jitra", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Kepala Batas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Kepelu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Kubang Pasu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Malau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 16, "name" => "Temin", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 17, "name" => "Kulim", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 17, "name" => "Lunas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 17, "name" => "Merbau Pulas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 17, "name" => "Padang Meha", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 17, "name" => "Sidam Kanan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 17, "name" => "Sungai Seluang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 18, "name" => "Kedawang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 18, "name" => "Kuah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 18, "name" => "Langkawi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 18, "name" => "Padang Masirat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 18, "name" => "Pulau Tuba", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 18, "name" => "Ulu Melaka", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 19, "name" => "Kuala Nerang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 19, "name" => "Padang Terap", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 19, "name" => "Tekai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 20, "name" => "Ayer Puteh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 20, "name" => "Guar Kepayang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 20, "name" => "Padang Peliang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 20, "name" => "Padang Pusing", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 20, "name" => "Pendang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 21, "name" => "Sik", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 22, "name" => "Guar Chempedak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 2, "district_id" => 22, "name" => "Yan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 23, "name" => "Bachok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 23, "name" => "Beklam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 23, "name" => "Mahligai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 23, "name" => "Tawang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Bertam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Chiku", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Galas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Gua Musang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Kuala Betis", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Limau Kasturi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Pasir Linggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 24, "name" => "Pasir Tumboh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 25, "name" => "Ayer Lanas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 25, "name" => "Batu Melintang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 25, "name" => "Jeli", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 25, "name" => "Kalai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 25, "name" => "Kuala Balah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 26, "name" => "Gong Kedak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Badang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Banggu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Beta", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Kadok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Kemumin", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Ketereh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Kota", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Kota Bharu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Kubang Kerian", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Limbat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Pendek", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Peringat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 27, "name" => "Salor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Aur Duri", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Bahagia", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Batu Jong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Batu Mengkebang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Bunut Saih", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Chegar Pinggang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Chenulang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Dabong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kampong Keroh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kampung Bedal", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kampung Guchil", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kampung Mia", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kampung Seladang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Karangan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kemubu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kuala Krai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Kuala Nal", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Mambong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Manek Urai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Olak Jeram", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Pasir Era", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Pasir Kelang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Slow", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Sungai Taku", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Tanjung Kala", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 28, "name" => "Temalir", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 29, "name" => "Labok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 29, "name" => "Machang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 29, "name" => "Pangkal Meleret", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 29, "name" => "Panyit", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 29, "name" => "Pulai Chondong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 29, "name" => "Temangan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 29, "name" => "Ulu Sat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Alor Pasir", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Bunut Susu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Chetok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Gual Periok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Kangkong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Kuala Lemal", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Kubang Gadong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Kubang Sepat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Pasir Mas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 30, "name" => "Rantau Panjang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Bukit Abal", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Bukit Awang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Bukit Jawa", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Gong Datok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Gong Serapat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Jeram", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Limbongan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Padang Pak Amat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Pasir Puteh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Selising", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 31, "name" => "Semerak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 32, "name" => "Bukit Panau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 32, "name" => "Jedok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 32, "name" => "Kusial", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 32, "name" => "Tanah Merah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 32, "name" => "Ulu Kusial", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 33, "name" => "Jal Besar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 33, "name" => "Kebakat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 33, "name" => "Pengkalan Kubor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 33, "name" => "Sungai Pinang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 33, "name" => "Terbok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 33, "name" => "Tumpat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 3, "district_id" => 33, "name" => "Wakaf Bharu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 4, "district_id" => 35, "name" => "Bandar Kuala Lumpur", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 4, "district_id" => 35, "name" => "Batu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 4, "district_id" => 35, "name" => "Dang Wangi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 4, "district_id" => 35, "name" => "Kuala Lumpur", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 5, "district_id" => 36, "name" => "None", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Alor Gajah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Ayer Limau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Durian Tunggal", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Gadek", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Kampung Tepat", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Kelemak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Kuala Linggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Lendu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Machap", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Masjid Tanah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Ramuan China Kechil", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Rembia", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Taboh Naning", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Tanjong Rimau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Tanjung Bidara", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 37, "name" => "Tebong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Asahan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Ayer Panas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Bemban", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Bukit Senggeh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Jasin", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Kesang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Merlimau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Rim", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Sempang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Semujok", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Serkam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 38, "name" => "Sungei Rambai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Ayer Keroh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Ayer Molek", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Bachang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Bandar Hilir", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Bandar Melaka", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Batu Berendam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Bukit Baru", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Bukit Katil", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Bukit Rambai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Duyong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Kesidang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Klebang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Kota Laksamana", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Krubong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Melaka Tengah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Pantai Kundor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Paya Rumput", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Sungai Udang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Tanjong Minyak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 6, "district_id" => 39, "name" => "Telok Mas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 41, "name" => "Jelebu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 41, "name" => "Kenaboi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 41, "name" => "Peradong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 42, "name" => "Jempol", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 42, "name" => "Serting Ulu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 43, "name" => "Johol", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 43, "name" => "Kuala Pilah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 43, "name" => "Pilah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 44, "name" => "Nilai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 45, "name" => "Jimah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 45, "name" => "Linggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 45, "name" => "Port Dickson", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 46, "name" => "Chembong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 46, "name" => "Pedas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 46, "name" => "Rembau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 47, "name" => "Ampangan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 47, "name" => "Bandar Seremban", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 47, "name" => "Jijan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 47, "name" => "Lenggeng", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 47, "name" => "Linggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 47, "name" => "Rantau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 47, "name" => "Seremban", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 48, "name" => "Ayer Kuning", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 48, "name" => "Gemas", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 48, "name" => "Gemencheh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 48, "name" => "Repah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 48, "name" => "Sungai Kelamah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 7, "district_id" => 48, "name" => "Tampin", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 49, "name" => "Bentong", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 49, "name" => "Bukit Tinggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 49, "name" => "Pelangai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 49, "name" => "Sabai", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 50, "name" => "Bera", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 50, "name" => "Durian Tawar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 50, "name" => "Kuala Bera", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 50, "name" => "Mengkarak", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 50, "name" => "Triang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 51, "name" => "Cameron Highlands", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 51, "name" => "Tanah Rata", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Burau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Jerantut", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Kota Gelanggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Kuala Tahan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Kuala Tembeling", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Pedah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Pulau Tawar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Sungai Tekam", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Tebing Tinggi", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Teh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Tembeling", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Ulu Cheka", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 52, "name" => "Ulu Tembeling", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Bandar Indera Mahkota", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Beserah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Bukit Sagu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Cherating", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Cherok Paloh", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Kuala Kuantan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Kuantan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Lepar Hilir", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Paya Bungor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Penor", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Sungai Karang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Tanjung Lumpur", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Ulu Kuantan", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 54, "name" => "Ulu Lepar", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Batu Yon", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Betau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Budu", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Chegar Perah", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Cheka", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Gua", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Jeransang", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Kechau", "created_at" => new Carbon(), "updated_at" => new Carbon()],
            ["state_id" => 8, "district_id" => 55, "name" => "Kuala Lipis", "created_at" => new Carbon(), "updated_at" => new Carbon()]
        ]);
    }
}
